day10/MyPortfolio/Models/Project.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MyPortfolio.Models
{
    public class Project
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        [DisplayName("프로젝트명")]
        public string ProjectName { get; set; }

        [Required]
        [MaxLength(400)]
        [DisplayName("프로젝트설명")]
        public string Description { get; set; }

        // 300X500 or 600 이미지      
        public string? FilePath { get; set; }
    }
}

day10/MyPortfolio/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Primitives;
using MyPortfolio.Data;
using MyPortfolio.Models;
using NuGet.Versioning;
using Westwind.AspNetCore.Markdown.Utilities;

namespace MyPortfolio.Controllers
{
    public class ProjectController : Controller
    {
        private readonly AppDbContext _context;

        public ProjectController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Project
        public async Task<IActionResult> Index()
        {
            return View(await _context.Project.ToListAsync());
        }

        // GET: Project/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Project/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProjectName,Description")] Project project, IFormFile FilePath)
        {
            if (ModelState.IsValid)
            {
                var fileUrl = ""; // if (ModelState.IsValid) 포함되는 지역변수로 변경

                if (FilePath != null && FilePath.Length > 0)
                {
                    //var fileUrl = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads", FilePath.FileName);

                    // 이미지파일 이름이 중복되지 않도록 랜덤으로 변경
                    var newFileName = "Mp_" + DateTime.Now.ToString("yyMMdd_HHmmssfff");

                    var extension = System.IO.Path.GetExtension(FilePath.FileName);

                    // FileStream으로 위경로에 파일 저장, 새롭게 변경된 파일명 지정
                    fileUrl = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads", newFileName + extension);

                    // 버퍼사용
                    using (var stream = System.IO.File.Create(fileUrl))
                    {
                        await FilePath.CopyToAsync(stream);
                    }
                }

                // 새로 변경된 이미지파일 경로를 Project 객체에 할당
                project.FilePath = fileUrl;
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // POST: Project/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProjectName,Description")] Project project, IFormFile FilePath)
        {            
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var fileUrl = "";
                try
                {
                    if (FilePath != null && FilePath.Length > 0)
                    {
                        
                        //var fileUrl = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads", FilePath.FileName);

                        // 이미지파일 이름이 중복되지 않도록 랜덤으로 변경
                        var newFileName = "Mp_" + DateTime.Now.ToString("yyMMdd_HHmmssfff");

                        var extension = System.IO.Path.GetExtension(FilePath.FileName);

                        // FileStream으로 위경로에 파일 저장, 새롭게 변경된 파일명 지정
                        fileUrl = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads", newFileName + extension);

                        // 버퍼사용
                        using (var stream = System.IO.File.Create(fileUrl))
                        {
                            await FilePath.CopyToAsync(stream);
                        }
                    }

                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }



        // GET: Project/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        

        // GET: Project/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _context.Project.FindAsync(id);
            if (project != null)
            {
                _context.Project.Remove(project);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return _context.Project.Any(e => e.Id == id);
        }
    }
}

day10/MyPortfolio/Views/Project/Create.cshtml
@model MyPortfolio.Models.Project

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @* 파일업로드시 중요한 부분은 enctype=multipart/form-data *@
        <form asp-controller="Project" asp-action="Create" 
              method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label"></label>
                <textarea asp-for="ProjectName" class="form-control"></textarea>
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilePath" class="control-label"></label>
                <input asp-for="FilePath" type="file" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script>
        var simplemde = new SimpleMDE({ element: document.getElementById("ProjectName") });
        var simplemde2 = new SimpleMDE({ element: document.getElementById("Description") });
    </script>
}

day10/MyPortfolio/Views/Project/Details.cshtml
@model MyPortfolio.Models.Project

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilePath)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

day10/MyPortfolio/Views/Project/Edit.cshtml
@model MyPortfolio.Models.Project

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label"></label>
                <textarea asp-for="ProjectName" class="form-control"></textarea>
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilePath" class="control-label"></label>
                <input asp-for="FilePath" type="file" class="form-control"></input>
                <span class="text-secondary">현재파일 : @Model.FilePath</span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script>
        var simplemde = new SimpleMDE({ element: document.getElementById("ProjectName") });
        var simplemde2 = new SimpleMDE({ element: document.getElementById("Description") });
    </script>
}

day10/MyPortfolio/Views/Project/Index.cshtml
@model IEnumerable<MyPortfolio.Models.Project>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProjectName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FilePath)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FilePath)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>